language: python
python:
  - '2.7'

addons:
    postgresql: "9.3"

env:
  global:
    # Eway sandbox keys to run system tests
    - secure: XSiuk44VhrgV94C7RW2X1A9XNVcwv78yZhjInH0dn4Otm2a5/1IepYZZvDHud2JMSF9V3j5G5ypsTNS9JFgpsNdgTJcMLKFQcJ3iSv7vwlUE66e6pGNdX9FA/RWfVlTaIxpRROCTEktGaP1ZpQ4DkJTD0JVxn0AeTntIzmLilAg=
    - secure: W+I/eWocDKoup1LVOQ5pthfaYcCyMyVJdof7L1K2/u0ulT+VwlkV8Ytuze9rRdEqH3wFTnv21pe6nEyBcDUTyzlhA8PjDAcRVr1gyXlF1lW6iE6wA/JKYLs1Xhu7Ob8UjMvutBroqauA7rbr5BJG//9qK+9wliX2QX8RH2g6syU=

  matrix:
    - TOXENV=py27-django14-oscar05-envtest
    - TOXENV=py27-django15-oscar05-envtest
    - TOXENV=py27-django16-oscar05-envtest

    - TOXENV=py27-django14-oscar06-envtest
    - TOXENV=py27-django15-oscar06-envtest
    - TOXENV=py27-django16-oscar06-envtest

    - TOXENV=py27-django14-oscar07-envtest
    - TOXENV=py27-django15-oscar07-envtest
    - TOXENV=py27-django16-oscar07-envtest

    - TOXENV=py27-django14-oscar08-envtest
    - TOXENV=py27-django15-oscar08-envtest
    - TOXENV=py27-django16-oscar08-envtest
    - TOXENV=py27-django17-oscar08-envtest
    
    - TOXENV=test-postgres-south-migrations
    - TOXENV=test-mysql-south-migrations
    - TOXENV=test-postgres-django-migrations
    - TOXENV=test-mysql-django-migrations

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - mysql -e 'create database devdb;'
  - psql -c 'create database devdb;' -U postgres

install:
    # Tox 1.8 installation required for new envlist generation feature
    # and can be removed after 1.8 is available on PyPI
  - pip install https://bitbucket.org/hpk42/tox/get/d835cca51418.zip

script:
  - tox
